name: Articles Branch CI

on:
  pull_request:
    branches: ["main"]

jobs:
  get-branch-info:
    runs-on: ubuntu-24.04
    outputs:
      dirs: ${{ steps.branch_info.outputs.dirs }}
      has_changes: ${{ steps.branch_info.outputs.has_changes }}
    steps:
      - name: Get fetch depth
        id: get_fetch_depth
        run: echo "fetch_depth=$(( commits + 1 ))" >> $GITHUB_OUTPUT
        env:
          commits: ${{ github.event.pull_request.commits }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ steps.get_fetch_depth.outputs.fetch_depth }}

      - name: get branch info
        id: branch_info
        run: |
          # Pull Requestののbaseとheadのdiffを取得し、*/main.typに変更があるディレクトリ一覧を抽出
          DIRS=$(git diff --name-status ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | awk '/\/main.typ/ { sub(/\/main.typ$/, "", $2); print $2 }')
          [ -n "$DIRS" ] && echo "has_changes=true" >> $GITHUB_OUTPUT
          # JSON形式にして出力
          echo "dirs=$(echo "$DIRS" | jq -R . | jq -s -c .)" >> $GITHUB_OUTPUT

  compile-articles:
    needs: get-branch-info
    runs-on: ubuntu-24.04
    if: needs.get-branch-info.outputs.has_changes
    strategy:
      matrix:
        dir: ${{ fromJson(needs.get-branch-info.outputs.dirs) }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Prepare Variables
        run: |
          if [ "$(uname -m)" = "x86_64" ]; then
            echo "TYPST_ARCH=x86_64-unknown-linux-musl" >> $GITHUB_ENV
          elif [ "$(uname -m)" = "arm64" ]; then
            echo "TYPST_ARCH=aarch64-unknown-linux-musl" >> $GITHUB_ENV
          else
            echo "Unsupported architecture: $(uname -m)"
            exit 1
          fi

      - name: Cache Typst
        uses: actions/cache@v4
        id: typst-cache
        with:
          path: /usr/local/bin/typst
          key: typst-${{ env.TYPST_ARCH }}
          restore-keys: |
            typst-${{ env.TYPST_ARCH }}

      - name: Install Typst
        if: steps.typst-cache.outputs.cache-hit != 'true'
        run: |
          cd /tmp
          curl -sSL $(curl -s https://api.github.com/repos/typst/typst/releases/latest | \
          jq -r '.assets[] | select(.name | contains("'${TYPST_ARCH}'") and endswith(".tar.xz")) | .browser_download_url') \
          -o typst.tar.xz && \
          tar -xvf typst.tar.xz --strip-components 1 && \
          install typst /usr/local/bin && \
          rm typst.tar.xz

      - name: Cache Fonts
        uses: actions/cache@v4
        id: fonts-cache
        with:
          path: |
            fonts
          key: fonts-${{ hashFiles('**/fonts.list') }}
          restore-keys: |
            fonts-${{ hashFiles('**/fonts.list') }}

      - name: Install Fonts
        if: steps.fonts-cache.outputs.cache-hit != 'true'
        run: make setup

      - name: compile article
        id: compile_article
        run: |
          cd "${{ github.workspace }}/${{ matrix.dir }}"
          make compile

          # ファルパスから "articles/" を削除し、"/" を "_" に置換
          ARTIFACT_NAME=$(echo "${{ matrix.dir }}" | sed 's|^articles/||' | tr '/' '_')
          mv main.pdf "${ARTIFACT_NAME}.pdf"

          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT

      - name: upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.compile_article.outputs.artifact_name }}.pdf.zip
          path: ${{ github.workspace }}/${{ matrix.dir }}/${{ steps.compile_article.outputs.artifact_name }}.pdf
          retention-days: 7

  comment-artifact:
    needs: compile-articles
    runs-on: ubuntu-24.04
    steps:
      - name: Post a comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ARTIFACTS_JSON=$(gh api /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)
          
          echo "## :tada:記事がビルドされました！:tada:" > comment.md
          echo "" >> comment.md

          # jqで各ArtifactのnameとIDを抽出してループ
          echo "$ARTIFACTS_JSON" | jq -r '.artifacts[] | "\(.name)\t\(.id)"' | while IFS=$'\t' read -r name id; do
            # 'owner/repo' を/で区切りownerとrepoを取得
            owner=$(echo "${{ github.repository }}" | cut -d'/' -f1)
            repo=$(echo "${{ github.repository }}" | cut -d'/' -f2)
            
            artifact_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${id}"
            preview_url="https://word-coins.github.io/artifact-previewer/?owner=${owner}&repo=${repo}&artifact_id=${id}"
            
            echo "- [${name}](${artifact_url}) ([プレビュー](${preview_url}))" >> comment.md
          done

          # 4. 共通フッターの追加
          job_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          expired_date=$(date --date "7 days" +%F)
          
          echo "" >> comment.md
          echo "有効期限 (おおよそ): ${expired_date}" >> comment.md
          echo "有効期限が切れた場合は [こちら](${job_url}) から「Re-run all jobs」を実行してください。" >> comment.md

          gh pr comment "${{ github.event.pull_request.html_url }}" --body-file comment.md --edit-last --create-if-none

